### ISSUE TITLE
The future of web & mobile app development - PWA

### ISSUE THREAD

**Issue by Tset-Noitamotua** [pybee/pybee.github.io#122]
It seems that [Progressive Web Apps][1] (PWA) will become popular in the future. Is the BeeWare project aware of this movement and will consider that on it's roadmap?

[1]: https://developers.google.com/web/progressive-web-apps/

**Comment by freakboy3742** [comment]
We're certainly aware of it; however, it's not something that is specifically on our roadmap. 

The problem is that it isn't a single technology, idea, or library, so you can't put something like "implement progressive web app" as a bullet point on a todo list. PWA is more of a philosophy for how to build web apps that behave nicely. From that perspective, we're totally on board - and BeeWare (and in particular, Toga for Web) aims to deliver apps that would meet the PWA goals.

**Comment by Tset-Noitamotua** [comment]
That's nice to hear. BeeWare has several [subprojects](https://github.com/pybee) that serve as cookiecutter templates for different platforms. Would be cool to see something like a "Python-PWA-templates" subproject or at least some PWA-examples in [Toga](https://github.com/pybee/toga) repo in the future.

**Comment by freakboy3742** [comment]
I think you're missing my point. What *is* a PWA app? What allows me to put a "PWA" label on my existing app? 

PWA isn't a platform. It isn't a library. It isn't a specific set of compliance criteria. Ultimately, PWA is little more than a marketing label that Google is using to describe sites that make good use of modern web tech. And sure - they're a desirable set of properties for a web app to have - but you have to use other technologies (like Django) to implement and deploy a PWA app. 

Thus a "PWA template" doesn't make much sense. However, we might be able to say "BeeWare's Django backend produces progressive web apps" . You could even argue it already is, to the extent that Toga's Django backend is fairly primitive, and as such, doesn't implement many app features.

**Comment by Tset-Noitamotua** [comment]
I got the point. Regard my post as a suggestion to utilize the term PWA as marketing for your Project ;-)
