### ISSUE TITLE
Uninstalling old app hangs / takes long time

### ISSUE THREAD

**Issue by oesah** [pybee/pybee.github.io#256]
```
[...]
Build complete.

Starting app on iPhone 7 Plus iOS 10.2
 * Starting simulator...
Waiting for device to boot...
 * Uninstalling old app version...
```

Stuck at that point (ran 15 mins already, tried multiple times). Seems to get stuck at roughly 90-95% on the apple loading bar.

Virtualenv: python 3.5, briefcase-0.2.1
MacOS: 10.11.6 (15G1611)
Command: `python setup.py ios -s`

Any ideas why and what to do?

**Comment by freakboy3742** [comment]
You've opened this ticket on the BeeWare website repository - I'm guessing this is meant as a report against Briefcase?

The startup process definitely shouldn't take 15 minutes - if there isn't obvious progress after about 30 seconds, it indicates something is wrong.

The best suggestion I can give is to start the simulator manually. Use Finder (or Xcode) to open the simulator app, and have it running in the background before running briefcase. Briefcase should connect to the existing simulator, and because it's not trying to coordinate booting the simulator, uploading an app, and starting an app all at the same time, it might be more reliable.

I'm going to close this particular ticket because it's definitely not a website issue; if what I've suggested doesn't work, feel free to reopen a new ticket [on the briefcase repository](https://github.com/pybee/briefcase).
