### ISSUE TITLE
"keep-informed" form not working with Disconnect add-on on Firefox

### ISSUE THREAD

**Issue by Ocupe** [pybee/pybee.github.io#36]
Clicking Subscribe on the form on the [keep-informed page](http://pybee.org/community/keep-informed/) leads to no effect, no mail, no user feedback. Tested on Firefox 48.0.1. 
The form is also rendered strange (no Bootstrap look), it looks like it falls back to default.
I also tested the form on Chrome, Opera and Safari, all three worked (and looked) as expected.

**Comment by glasnt** [comment]
Hi @Ocupe! Thanks for the report. 

The styles definitely need to be addressed. I'll get onto this

As for the functionality; this is base MailChimp form. If I test it under Firefox (47.0.1), I get a green message added to the page after submitting that says "Almost finished... We need to confirm your email address." Can you confirm you have no extensions that block third-party JavaScript or otherwise?

I'll run my test again once I get the v48 update and see if the small version change makes any difference.

**Comment by Ocupe** [comment]
Hi,
I tested it again in a virtual machine and it worked for me in Firefox 47 and 48 sorry for the wrong infos. Probably still interesting is that the [Disconnect  Add-On](https://addons.mozilla.org/en-US/firefox/addon/disconnect/) was the thing that blocked the request to MailChimp. It is a Firefox featured add-on with 293,243 users at  the moment. I don't know if we can do anything about how MailChimp and Disconnect are working together, but if we can, I thing we should. :)

**Comment by glasnt** [comment]
Hi @Ocupe. It looks like you can explicitly add mailchimp to your whitelist in Disconnect, if that's something you want to do, but signing up to a newsletter is only a one-time action. 

Perhaps in the future you can, as with any other site that you want to re-enable functionality that's blocked by third-party apps, you temporarily disable the blocker. Your milage may vary, as this is explicitly taking down your privacy walls.
